package javaform;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javaform.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author INSTIKI
 */
public class frm01 extends javax.swing.JFrame {
    DefaultTableModel TM = new DefaultTableModel();

    /**
     * Creates new form frm01
     */
    public frm01() throws SQLException {
        initComponents();
        tbmhs.setModel(TM);
        TM.addColumn("NIM");
        TM.addColumn("NAMA");
        TM.addColumn("PRODI");
        
        ListDataMahasiswa();
        
        txNIM.setText("");
        txNAMA.setText("");
        txPRODI.setText("");
        txTGLAHIR.setText("");
        txJK.setText("");
        
        String[] txprodi = {"Pilih Prodi","Informatika","Rekayasa System Komputer","Bisnis Digital","Desain Komunikasi Visual"};
        cboPRODI.removeAllItems();
        cboPRODI.addItem(txprodi[0]);
        cboPRODI.addItem(txprodi[1]);
        cboPRODI.addItem(txprodi[2]);
        cboPRODI.addItem(txprodi[3]);
        cboPRODI.addItem(txprodi[4]);
        cboPRODI.setSelectedIndex(0);  
        cboPRODI.setVisible(false);
        
        cboJK.removeAllItems();
        cboJK.addItem("Pilih Jenis Kelamin");
        cboJK.addItem("Laki-Laki");
        cboJK.addItem("Perempuan");
        cboJK.setSelectedIndex(0);
        cboJK.setVisible(false);
    }
    private void ListDataMahasiswa() throws SQLException{
        Connection cnn = koneksi();
        
        if(!cnn.isClosed()){
            // membaca tabel mahasiswa
            PreparedStatement PS = cnn.prepareStatement("SELECT * FROM mahasiswa");
            ResultSet RS = PS.executeQuery();
            
            TM.getDataVector().removeAllElements();
            TM.fireTableDataChanged();
            
            while( RS.next() ){
                Object[] dta = new Object[3];
                    dta[0] = RS.getString("NIM");
                    dta[1] = RS.getString("NAMA");
                    dta[2] = RS.getString("PRODI");
                    
                TM.addRow(dta);
            }
            cnn.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmhs = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        cmdTutup = new javax.swing.JButton();
        cmdDataBaru = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txPRODI = new javax.swing.JTextField();
        cboPRODI = new javax.swing.JComboBox<>();
        txJK = new javax.swing.JTextField();
        cboJK = new javax.swing.JComboBox<>();
        txTGLAHIR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txALAMAT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txNOTELP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txEMAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        cmdHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        tbmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "PRODI", "JENISKELAMIN", "TGL LAHIR"
            }
        ));
        tbmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmhs);

        cmdTutup.setText("Tutup");
        cmdTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTutupActionPerformed(evt);
            }
        });

        cmdDataBaru.setText("Data Baru");
        cmdDataBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDataBaruActionPerformed(evt);
            }
        });

        jLabel2.setText("NIM");

        jLabel3.setText("NAMA");

        txNAMA.setText("jTextField2");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Prodi");

        jLabel6.setText("TGL Lahir");

        txPRODI.setText("jTextField3");

        cboPRODI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txJK.setText("jTextField4");

        cboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txTGLAHIR.setText("jTextField5");

        jLabel7.setText("Alamat");

        txALAMAT.setText("jTextField1");

        jLabel8.setText("No Telp.");

        txNOTELP.setText("jTextField2");

        jLabel9.setText("EMAIL");

        txEMAIL.setText("jTextField3");

        jLabel10.setText("Status Kelas");

        jTextField4.setText("jTextField4");

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmdDataBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdHapus))
                                    .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboJK, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txALAMAT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txTGLAHIR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txNOTELP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(524, 524, 524)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdDataBaru, cmdHapus});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDataBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdHapus))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txNOTELP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTGLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdDataBaru, cmdHapus});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTutupActionPerformed
        if(cmdTutup.getText().equals("Tutup")){
            int opsi = JOptionPane.showOptionDialog(
                    this, 
                    "Yakin Akan Menutup Aplikasi?", 
                    "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    null, 
                    null);
            if(opsi == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_cmdTutupActionPerformed
    
    private void clearForm(){
        txNIM.setText("");
        txNAMA.setText("");
        txTGLAHIR.setText("");
    }
    private void StoreData() throws SQLException{
        String nim = txNIM.getText();
        String nama = txNAMA.getText();
        String tgllahir = txTGLAHIR.getText();
        String prodi = String.valueOf( cboPRODI.getSelectedItem() );
        String jk = String.valueOf( cboJK.getSelectedItem());
        String jkx = "0";
        if(jk.equals("Perempuan")){
            jkx = "1";
        }
        
        Connection cnn = koneksi();
        if(! cnn.isClosed() ){
            PreparedStatement PS = cnn.prepareStatement("INSERT INTO mahasiswa(NIM,NAMA,PRODI,JENISKELAMIN,TGLLAHIR) VALUES(?,?,?,?,?)");
            PS.setString(1, nim);
            PS.setString(2, nama);
            PS.setString(3, prodi);
            PS.setString(4, jkx);
            PS.setDate(5, java.sql.Date.valueOf(tgllahir));
            PS.executeUpdate();
            
            cnn.close();
            
        }
        
        
                
    }
    private void cmdDataBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDataBaruActionPerformed
        
        if(cmdDataBaru.getText().equals("Data Baru")){
            cmdDataBaru.setText("Simpan Data");
            cboPRODI.setVisible(true);
            txPRODI.setVisible(false);
            cboJK.setVisible(true);
            txJK.setVisible(false);
            clearForm();
        }else{
            cmdDataBaru.setText("Data Baru");
            cboPRODI.setVisible(false);
            txPRODI.setVisible(true);
            cboJK.setVisible(false);
            txJK.setVisible(true);
            
            try {
                StoreData();
                ListDataMahasiswa();
            } catch (SQLException ex) {
                Logger.getLogger(frm01.class.getName()).log(Level.SEVERE, null, ex);
            }
            clearForm();
            
        }
        
    }//GEN-LAST:event_cmdDataBaruActionPerformed

    private void tbmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmhsMouseClicked
        String nim = tbmhs.getValueAt( tbmhs.getSelectedRow(), 0).toString();
        String nm = tbmhs.getValueAt( tbmhs.getSelectedRow(), 1).toString();
        String prodi = tbmhs.getValueAt( tbmhs.getSelectedRow(), 2).toString();
        
        String jkx = "";
        String alamat = "";
        String notelp = "";
        String email = "";
        String sttkelas = "";
        
        Connection cnn = koneksi();
        try {
            if(!cnn.isClosed()){
                PreparedStatement PS = cnn.prepareStatement("SELECT * FROM mahasiswa WHERE NIM=? AND NAMA=?");
                PS.setString(1, nim);
                PS.setString(2, nm);
                ResultSet RS = PS.executeQuery();
                while(RS.next()){
                    jkx = RS.getString("JENISKELAMIN");
                    alamat = RS.getString("ALAMAT");
                    notelp = RS.getNString("NOTELP");
                    email = RS.getString("EMAIL");
                    sttkelas = RS.getString("STASTUSKELAS");
                }
                cnn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm01.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //SimpleDateFormat fm = new SimpleDateFormat("yyyy-mm-dd");
                       
        txNIM.setText(nim);
        txNAMA.setText(nm);
        txPRODI.setText(prodi);
        txJK.setText(jkx);
        txALAMAT.setText(alamat);
        txEMAIL.setText(email);
        txNOTELP.setText(notelp);    
    }//GEN-LAST:event_tbmhsMouseClicked

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        String nim = txNIM.getText();
        
        Connection cnn = koneksi();
        try {
            if(!cnn.isClosed()){
                PreparedStatement PS = cnn.prepareStatement("DELETE FROM mahasiswa WHERE NIM=?");
                PS.setString(1, nim);
                PS.executeUpdate();
                cnn.close();
                ListDataMahasiswa();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm01.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmdHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm01().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm01.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboJK;
    private javax.swing.JComboBox<String> cboPRODI;
    private javax.swing.JButton cmdDataBaru;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tbmhs;
    private javax.swing.JTextField txALAMAT;
    private javax.swing.JTextField txEMAIL;
    private javax.swing.JTextField txJK;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txNOTELP;
    private javax.swing.JTextField txPRODI;
    private javax.swing.JTextField txTGLAHIR;
    // End of variables declaration//GEN-END:variables
}
